### ISSUE TITLE
Biometric authentication on Brave

### ISSUE THREAD

**Issue by probablypablito** [quexten/goldwarden#104]
The Bitwarden extension gives an error when attempting to set up biometrics. This initial issue I solved by downloading Chrome, re running the `goldwarden setup browserbiometrics` command, and then copying the file from the Chrome config folder to Brave's.  Now, however, when pressing set up biometrics in the extension nothing occurs. 

I saw this mentioned in #54 but it seems it was closed.

**Comment by quexten** [comment]
Is Brave installed as a Flatpak/Snap or natively (deb/rpm/aur/etc.)

**Comment by probablypablito** [comment]
I tried the Flatpak first but later switched to the deb per the wiki's instructions. The issues I'm describing happened on the deb.

**Comment by quexten** [comment]
Took a while to circle back around to this.

Most likely the binary called by brave/chrome does not find the correct socket path. This should be fixed in the latest main branch build. You could try on the latest main branch build. If that does not work, you can enable debug logging for the browser biometrics integration by building with `go build -tags debuglogging .`, which places the logs at `/tmp/DELETE_ME.log `

**Comment by quexten** [comment]
Just released v0.2.12 which should include the fix. When you are able, feel free to update and check if it's fixed for you.

**Comment by probablypablito** [comment]
Just updated (removed Flatpak Goldwarden and installed .deb). The issue still seems to persist. I was able to login into my Bitwarden successfully and approve login requests but got the "Browser integration is not set up" error.  Running `goldwarden setup browserbiometrics` did say it created `/home/user/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts/` though. I rebooted as well just in case but to no avail. If you need any files / screenshots from me let me know.

**Comment by quexten** [comment]
On 0.2.12 it should create 2 files, in the NativeMessagingHosts folder, goldwarden-proxy.sh and com.8bit.bitwarden.json. Can you copy paste the contents of those 2 files? Also, what's the output of `which goldwarden`.

>  I rebooted as well just in case but to no avail. If you need any files / screenshots from me let me know

Reboot is not required, but restarting the browser is.

**Comment by probablypablito** [comment]
```bash
$ which goldwarden
/usr/bin/goldwarden
```

Upon checking the contents of  `/home/user/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts/` with `ls -la` there appear to be no files there... Nothing is created after running `goldwarden setup browserbiometrics` even after I remove the folder and the command creates the folder.

**Comment by quexten** [comment]
Can you download the "_debug" build from here: https://github.com/quexten/goldwarden/actions/runs/7946907229 and re-run "goldwarden setup browserbiometrics" (or ./goldwarden_linux_x86_64_debug setup browserbiometrics) and post the output?

**Comment by probablypablito** [comment]
```bash
(~/Downloads) $ ./goldwarden_debug setup browserbiometrics
Created native messaging host directory: /home/user/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts/
Done.
(~/Downloads) $ ls -la /home/user/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts/

total 8
drwxr-xr-x  2 user user 4096 Feb 18 10:59 .
drwx------ 37 user user 4096 Feb 18 10:59 ..
```

I didn't log in beforehand or remove the existing Goldwarden installation and I deleted the NativeMessagingHosts folder before running the command.

**Comment by felixfrank** [comment]
I have the same issue in the current release installed with yay on archlinux.
I think the problem is in terminating the `detectAndInstallBrowsers` function when there are more than 3 `/` in the path, whereas the brave path should have 4 of them?

https://github.com/quexten/goldwarden/blob/80d476a9b529045b8c5fd2a439b31099ead74feb/browserbiometrics/main.go#L107C1-L109C4/

**Comment by quexten** [comment]
Sadly, I'm a bit time-constrained atm so I can't triage it properly, but I have bumped the search depth to 5. @felixfrank if you have time, feel free to test the main branch, otherwise I'll try to create a release soon, so it's available on the AUR.

**Comment by quexten** [comment]
@probablypablito , @felixfrank does this work for you now that the search depth is 5?

**Comment by quexten** [comment]
Seems to work on latest main:
```
Writing new manifest
Writing new proxy script
Found chrome-like browser: /home/quexten/.config/BraveSoftware/Brave-Browser-Beta/NativeMessagingHosts
Removing old manifest and proxy script
Writing new manifest
Writing new proxy script
Found chrome-like browser: /home/quexten/.config/BraveSoftware/Brave-Browser-Nightly/NativeMessagingHosts
```

So closing for now, feel free to re-open/comment if it does not.
